# Revision Examples

In [37]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
from numpy.random import randint, randn

## Numpy Arrays

In [38]:
arr = randint(101,124)
arr

114

In [39]:
arr = randint(101,124, size=10)
arr

array([106, 104, 101, 101, 112, 101, 118, 115, 114, 106])

In [40]:
# arr = randint(101,124, size=24).reshape(4,6)
arr = randint(101,124, size=(4,6))
arr

array([[123, 104, 117, 110, 123, 104],
       [117, 122, 107, 122, 119, 112],
       [109, 111, 119, 119, 107, 117],
       [102, 110, 102, 107, 122, 122]])

In [41]:
np.sum(arr, axis=1)

array([681, 699, 682, 665])

In [42]:
arr[np.sum(arr, axis=1) > 680]

array([[123, 104, 117, 110, 123, 104],
       [117, 122, 107, 122, 119, 112],
       [109, 111, 119, 119, 107, 117]])

## Pandas DataFrame

In [43]:
df = DataFrame(arr, columns=['a','b','c','d','e','f'])
df

a    b    c    d    e    f
0  123  104  117  110  123  104
1  117  122  107  122  119  112
2  109  111  119  119  107  117
3  102  110  102  107  122  122

In [44]:
df.loc[2]

a    109
b    111
c    119
d    119
e    107
f    117
Name: 2, dtype: int32

In [45]:
df.b.mean()

111.75

In [46]:
df[df['c'] > 110]

a    b    c    d    e    f
0  123  104  117  110  123  104
2  109  111  119  119  107  117

In [47]:
df[(df.c > 110) & (df.c < 120)]

a    b    c    d    e    f
0  123  104  117  110  123  104
2  109  111  119  119  107  117

In [51]:
df.reindex(columns = ['a','b','c'])
df

a    b    c    d    e    f
0  123  104  117  110  123  104
1  117  122  107  122  119  112
2  109  111  119  119  107  117
3  102  110  102  107  122  122

In [31]:
df.rename(columns={'a':'A'})

A    b    c    d    e    f
0  117  114  107  112  115  113
1  120  115  109  119  103  115
2  115  105  105  117  116  117
3  101  103  107  114  122  103

In [32]:
ls = list((np.sum(arr, axis=1)))
ls

[678, 681, 675, 650]

In [33]:
ls.sort()
ls

[650, 675, 678, 681]

In [34]:
ls.reverse()
ls

[681, 678, 675, 650]

## Print a Pattern

In [60]:
n = 5
ch = '*'
for x in range(n):
    print(ch * (x+1))

*
**
***
****
*****


In [61]:
n = 5
ch = '*'
for x in range(n):
    print(ch * (n-x))

*****
****
***
**
*


In [72]:
n=5
for i in range(n):
    for j in range(0, n - i):
        print(" ", end=" ")
    for k in range(n - i, n):
        print("*", end=" ")
    print("")


          
        * 
      * * 
    * * * 
  * * * * 
